version: '3'
services:
  grafana:
    image: bitnami/grafana:8.4.4
    container_name: grafana
    ports:
    - 3000:3000
    environment:
      GF_INSTALL_PLUGINS: redis-datasource:2.1.1,redis-app:2.2.1
    volumes:
      - C:\Grafana:/bitnami/grafana/data

  redis:
    image: bitnami/redis:6.0.16
    container_name: redis
    ports:
    - 6379:6379
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - C:\Redis:/bitnami/redis/data

  zookeeper:
    image: bitnami/zookeeper:3.6.3
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - 2181:2181
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
      ZOO_PORT_NUMBER: 2181
      ZOO_TICK_TIME: 2000
      ZOO_INIT_LIMIT: 5
      ZOO_SYNC_LIMIT: 2
      ZOO_SERVERS: zookeeper:2888:3888
    restart: always

  kafka:
    image: bitnami/kafka:3.1.0
    container_name: kafka
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_LISTENERS: CLIENT://:29092,EXTERNAL://:9092
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: CLIENT
      KAFKA_CFG_ADVERTISED_LISTENERS: CLIENT://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CFG_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    restart: always

  nimbus:
    image: storm:2.3.0
    container_name: nimbus
    hostname: nimbus
    command: storm nimbus
    depends_on:
      - zookeeper
    ports:
      - 3773:3773
      - 3772:3772
      - 6627:6627
    restart: always
    
  supervisor:
    image: storm:2.3.0
    container_name: supervisor
    command: storm supervisor
    depends_on:
      - zookeeper
      - nimbus
    ports:
      - 8000:8000
      - 6700:6700
      - 6701:6701
      - 6702:6702
      - 6703:6703
    restart: always

  storm-ui:
    image: storm:2.3.0
    container_name: storm-ui
    command: storm ui
    depends_on:
      - nimbus
      - zookeeper
    ports:
      - 8080:8080

  topology:
    image: storm:2.3.0
    container_name: topology
    command: storm jar /topology.jar com.alawresz.twitterment.App
    depends_on:
      - kafka
      - nimbus
      - zookeeper
      - supervisor
    volumes:
      - .\topology.jar:/topology.jar
    env_file:
      - .env